# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: election.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65lection.proto\x12\x08\x65lection\"\"\n\x0fServeClientArgs\x12\x0f\n\x07Request\x18\x01 \x01(\t\"C\n\x10ServeClientReply\x12\x0c\n\x04\x44\x61ta\x18\x01 \x01(\t\x12\x10\n\x08LeaderID\x18\x02 \x01(\t\x12\x0f\n\x07Success\x18\x03 \x01(\x08\"c\n\x12RequestVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\x05\x12\x14\n\x0clastLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0blastLogTerm\x18\x04 \x01(\x05\"V\n\x13RequestVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0cvote_granted\x18\x02 \x01(\x08\x12\x1b\n\x13previousleaderlease\x18\x04 \x01(\x05\"\xa7\x01\n\x14RequestAppendEntries\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x10\n\x08leaderId\x18\x02 \x01(\x05\x12\x14\n\x0cprevLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0bprevLogTerm\x18\x04 \x01(\x05\x12\x14\n\x0cleaderCommit\x18\x05 \x01(\x05\x12\x0f\n\x07\x65ntries\x18\x06 \x03(\t\x12\x1d\n\x15leaseintervalduration\x18\x07 \x01(\x05\"C\n\x15ResponseAppendEntries\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0b\n\x03\x61\x63k\x18\x02 \x01(\x05\x12\x0f\n\x07success\x18\x03 \x01(\x08\x32\xf4\x01\n\x08\x45lection\x12\x46\n\x0bServeClient\x12\x19.election.ServeClientArgs\x1a\x1a.election.ServeClientReply\"\x00\x12L\n\x0bRequestVote\x12\x1c.election.RequestVoteRequest\x1a\x1d.election.RequestVoteResponse\"\x00\x12R\n\rAppendEntries\x12\x1e.election.RequestAppendEntries\x1a\x1f.election.ResponseAppendEntries\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'election_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SERVECLIENTARGS']._serialized_start=28
  _globals['_SERVECLIENTARGS']._serialized_end=62
  _globals['_SERVECLIENTREPLY']._serialized_start=64
  _globals['_SERVECLIENTREPLY']._serialized_end=131
  _globals['_REQUESTVOTEREQUEST']._serialized_start=133
  _globals['_REQUESTVOTEREQUEST']._serialized_end=232
  _globals['_REQUESTVOTERESPONSE']._serialized_start=234
  _globals['_REQUESTVOTERESPONSE']._serialized_end=320
  _globals['_REQUESTAPPENDENTRIES']._serialized_start=323
  _globals['_REQUESTAPPENDENTRIES']._serialized_end=490
  _globals['_RESPONSEAPPENDENTRIES']._serialized_start=492
  _globals['_RESPONSEAPPENDENTRIES']._serialized_end=559
  _globals['_ELECTION']._serialized_start=562
  _globals['_ELECTION']._serialized_end=806
# @@protoc_insertion_point(module_scope)
